/**
 * Generates placeholder assets for the portfolio:
 *   public/resume.pdf   — one-page placeholder, wired to the hero "Download Resume" button
 *   public/og-image.png — 1200x630 social preview card, referenced by the Open Graph tags
 *
 * Re-run anytime with: npm run generate:assets
 */
import { writeFileSync, mkdirSync } from 'node:fs'
import { deflateSync } from 'node:zlib'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const publicDir = join(root, 'public')
mkdirSync(publicDir, { recursive: true })

/* ---------------- resume.pdf ---------------- */

function buildResumePdf() {
  const textLines = [
    { size: 30, x: 72, y: 690, text: 'Dinesh Prasad' },
    {
      size: 12,
      x: 72,
      y: 662,
      text: 'Aspiring Software Engineer  |  Cyber Security Enthusiast',
    },
    { size: 11, x: 72, y: 628, text: 'This is a placeholder resume generated by the portfolio scaffold.' },
    { size: 11, x: 72, y: 610, text: 'Replace public/resume.pdf with your real resume file to activate' },
    { size: 11, x: 72, y: 592, text: 'the "Download Resume" button in the hero section.' },
  ]

  // Red accent bar + text, Helvetica
  let content = 'q 1 0.125 0.157 rg 72 722 170 6 re f Q\n'
  for (const l of textLines) {
    content += `BT /F1 ${l.size} Tf ${l.x} ${l.y} Td (${l.text}) Tj ET\n`
  }

  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>',
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
    `<< /Length ${Buffer.byteLength(content)} >>\nstream\n${content}endstream`,
  ]

  let pdf = '%PDF-1.4\n'
  const offsets = []
  objects.forEach((body, i) => {
    offsets.push(Buffer.byteLength(pdf))
    pdf += `${i + 1} 0 obj\n${body}\nendobj\n`
  })

  const xrefStart = Buffer.byteLength(pdf)
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`
  offsets.forEach((o) => {
    pdf += `${String(o).padStart(10, '0')} 00000 n \n`
  })
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF`

  return Buffer.from(pdf, 'latin1')
}

/* ---------------- og-image.png ---------------- */

const CRC_TABLE = new Int32Array(256)
for (let n = 0; n < 256; n++) {
  let c = n
  for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1
  CRC_TABLE[n] = c
}

function crc32(buf) {
  let crc = -1
  for (let i = 0; i < buf.length; i++) crc = (crc >>> 8) ^ CRC_TABLE[(crc ^ buf[i]) & 0xff]
  return (crc ^ -1) >>> 0
}

function pngChunk(type, data) {
  const len = Buffer.alloc(4)
  len.writeUInt32BE(data.length)
  const typeBuf = Buffer.from(type, 'ascii')
  const crc = Buffer.alloc(4)
  crc.writeUInt32BE(crc32(Buffer.concat([typeBuf, data])))
  return Buffer.concat([len, typeBuf, data, crc])
}

function buildOgImage(width, height) {
  const INK = [8, 8, 8] // #080808
  const RED = [255, 32, 40] // #FF2028

  const raw = Buffer.alloc(height * (1 + width * 3))
  let off = 0
  for (let y = 0; y < height; y++) {
    raw[off++] = 0 // filter: none
    for (let x = 0; x < width; x++) {
      let [r, g, b] = INK
      // center red band
      if (y >= 286 && y < 344) [r, g, b] = RED
      // thin red rule near the bottom
      if (y >= 552 && y < 556 && x >= 96 && x < width - 96) [r, g, b] = RED
      raw[off++] = r
      raw[off++] = g
      raw[off++] = b
    }
  }

  const ihdr = Buffer.alloc(13)
  ihdr.writeUInt32BE(width, 0)
  ihdr.writeUInt32BE(height, 4)
  ihdr[8] = 8 // bit depth
  ihdr[9] = 2 // color type: RGB
  ihdr[10] = 0 // compression
  ihdr[11] = 0 // filter
  ihdr[12] = 0 // interlace

  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    pngChunk('IHDR', ihdr),
    pngChunk('IDAT', deflateSync(raw, { level: 9 })),
    pngChunk('IEND', Buffer.alloc(0)),
  ])
}

/* ---------------- write ---------------- */

writeFileSync(join(publicDir, 'resume.pdf'), buildResumePdf())
writeFileSync(join(publicDir, 'og-image.png'), buildOgImage(1200, 630))
console.log('Generated public/resume.pdf and public/og-image.png')
